# Generated by Django 5.0.2 on 2024-02-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_player_bracket_alter_match_bracket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scoring_type',
            field=models.CharField(choices=[('Side Out', 'Side out scoring'), ('Rally', 'Rally Scoring')], default='Side Out', max_length=8),
            preserve_default=False,
        ),
    ]
