# Generated by Django 5.0.2 on 2024-02-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_match_scoring_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner_for_player', to='MyApp.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='scoring_type',
            field=models.CharField(choices=[('Side Out', 'Side out scoring'), ('Rally', 'Rally scoring')], max_length=8),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_with_stats', to='MyApp.player'),
        ),
    ]
