# Generated by Django 5.0.2 on 2024-02-14 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_playerstats_opponent1_playerstats_opponent2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='opponent1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='opponent1', to='MyApp.player'),
        ),
    ]
