# Generated by Django 5.0.2 on 2024-02-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_alter_playerstats_opponent1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='teams',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
