# Generated by Django 5.0.2 on 2024-02-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_remove_match_match_date_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='resets_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='resets_missed',
            field=models.IntegerField(default=0),
        ),
    ]
