# Generated by Django 5.0.2 on 2024-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_playerstats_resets_made_playerstats_resets_missed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='putaway_losers',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='lob_successes',
            field=models.IntegerField(default=0),
        ),
    ]
