# Generated by Django 5.0.2 on 2024-02-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_remove_playerstats_putaway_losers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='third_drives',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='third_drops',
            field=models.IntegerField(default=0),
        ),
    ]
