# Generated by Django 5.0.2 on 2024-02-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_playerstats_third_drives_playerstats_third_drops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='drop_misses',
            new_name='third_drop_misses',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='drop_winners',
            new_name='third_drop_winners',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='third_drop_makes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='thirds',
            field=models.IntegerField(default=0),
        ),
    ]
