# Generated by Django 5.0.2 on 2024-02-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_playerstats_atp_losers_playerstats_atp_misses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.CharField(choices=[('R', 'Right'), ('L', 'Left')], default='R', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='sponsor',
            field=models.CharField(default='Joola', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='turned_pro',
            field=models.CharField(default='2017', max_length=4),
            preserve_default=False,
        ),
    ]
